app:
  app_config_file: !ENV ${PATH_TO_ANALYSIS_APP}/home/config/app/
  execution_summary:
    type: file-v2
    execution_summary_dir: !ENV ${PATH_TO_ANALYSIS_APP}/home/data/exe_history
  user_repo:
    type: file
    data_file: !ENV ${PATH_TO_ANALYSIS_APP}/home/config/usr/users.json
  sch_repo:
    type: file
    data_file: !ENV ${PATH_TO_ANALYSIS_APP}/home/config/scheduler/sch.json